# Imagen base con Java
FROM openjdk:17-jdk-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar el .jar compilado al contenedor
COPY build/libs/*.jar appjava.jar

# Exponer el puerto donde corre Spring Boot
EXPOSE 8080

# Comando para arrancar la app
ENTRYPOINT ["java", "-jar", "appjava.jar"]
