services:
  api:
    build: .
    container_name: api-usuarios
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
      - /app/node_modules
      - sqlite_data:/app/src/db

volumes:
  sqlite_data:
