version: "3.9"

services:
  api:
    build: .
    container_name: api-users
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - sqlite_data:/app/src/db
    environment:
      - NODE_ENV=development

volumes:
  sqlite_data:
