# Etapa 1: usar solo JDK
FROM eclipse-temurin:21-jdk-jammy AS build
WORKDIR /app

# Copiar todos los archivos, incluyendo gradlew
COPY . .

# Dar permisos a gradlew y construir
RUN chmod +x gradlew
RUN ./gradlew clean build -x test

# Etapa 2: imagen final ligera solo JRE
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
