version: "3.8"

services:
  php:
    image: php:8.2-apache
    container_name: php-crud
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    environment:
      TZ: Europe/Madrid
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-crud
    restart: always
    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: crud_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: